apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonita-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bonita
  template:
    metadata:
      labels:
        app: bonita
    spec:
      initContainers:
      - name: copy-config
        image: busybox
        command: ['sh', '-c', 'cp -f /tmp/* /config/']
        volumeMounts:
        - name: scripts
          mountPath: /tmp
        - name: config-volume
          mountPath: /config
      containers:
      - name: bonita-container
        image: bonita:2023.2
        ports:
        - containerPort: 8080
        env:
        - name: TENANT_LOGIN
          value: admin
        - name: TENANT_PASSWORD
          value: plop
        - name: DB_VENDOR
          value: postgres
        - name: DB_HOST
          value: bonita-db-service
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: bonita
        - name: DB_USER
          value: bonita
        - name: DB_PASS
          value: bpm
        - name: BIZ_DB_NAME
          value: business_data
        - name: BIZ_DB_USER
          value: business_data
        - name: BIZ_DB_PASS
          value: bpm
        volumeMounts:
        - name: config-volume
          mountPath: /opt/bonita/conf/logs
      volumes:
      - name: config-volume
        emptyDir: {}
      - name: scripts
        configMap:
          name: bonita-logs-config

